export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REFRESH_TOKENS = 'AUTH_REFRESH_TOKENS';
export const AUTH_AUTO_REFRESH_TOKENS = 'AUTH_AUTO_REFRESH_TOKENS';